[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cd client && npm install",
  "cd client && npm run build",
  "cd ../server && npm install"
]

[start]
cmd = "npm run start:prod"

